## 1. Write a function so that the columns of the output matrix are powers of the inputvector.

### The order of the powers is determined by the increasing boolean argument. Specifically, whenincreasing is False, the i-th output column is the input vector raised element-wise to the powerof N - i - 1.

### HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [5]:
import numpy as np
def Vandermonde_matrix(inp_vector,n,increasing = False):
    if not increasing:
        out_matrix = np.array([x**(n-i-1)for x in inp_vector for i in range(n)]).reshape(inp_vector.size,n)
    elif increasing:
        out_matrix = np.array([x** i for x in inp_vector for i in range(n)]).reshape(inp_vector.size,n)
    return out_matrix

inputvector = np.array([1,2,3,4,5])
no_col_opmat = 3
op_matx_dec_order = Vandermonde_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = Vandermonde_matrix(inputvector,no_col_opmat,True)

In [6]:
op_matx_dec_order

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [7]:
op_matx_inc_order

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]])

## 2. Write a function to find moving average in an array over a window.
#### Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [15]:
import numpy as np

def moving_average(input_array, k=3) :
    shape = input_array.shape[0]
    
    #Create a vector of zeroes with the shape as n-k+1
    
    array_moving_avg = np.zeros(shape - k + 1)
    
    # Iterate over the input array. While doing so, for every element, get the next k elements through slicing, 
    # computer their mean and add to the output array.
    
    for i in range(k, shape + 1):
        array_moving_avg[i-k] = input_array[i-k:i].mean()
    
    return array_moving_avg   


a = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window_size = 3
moving_average_arr = moving_average(a, window_size)
print("The moving average sequence has", moving_average_arr.shape[0], "values.")

The moving average sequence has 11 values.


In [16]:
moving_average_arr

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])